{% set name = "runs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/runs-{{ version }}.tar.gz
  sha256: cca304b631dbefec598c7bfbcfb50d6feace6d3a968734b67fd42d3c728f5a05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - xmod

test:
  imports:
    - runs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rec/runs
  summary: 🏃 Run a block of text as a subprocess  🏃
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
